fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: pretty-format-json
        args: [ '--autofix', '--no-sort-keys' ]

  - repo: local
    hooks:
      - id: gci
        name: gci
        entry: gci write --skip-generated -s standard -s default -s blank -s dot -s alias -s localmodule
        language: golang
        files: \.go$
        types: [ file ]

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.62.0
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args: [ --ignore, DL3007, --ignore, DL3008, --ignore, DL3016 ]
